// Code generated by protoc. DO NOT EDIT.
package pb

// GetRequest - Get RPC 请求
type GetRequest struct {
	Key string
}

// GetResponse - Get RPC 响应
type GetResponse struct {
	Value     string
	Version   int64
	Error     string
	RaftIndex int64
}

// PutRequest - Put RPC 请求
type PutRequest struct {
	Key     string
	Value   string
	Version int64
}

// PutResponse - Put RPC 响应
type PutResponse struct {
	Success    bool
	NewVersion int64
	Error      string
	RaftIndex  int64
}

// DeleteRequest - Delete RPC 请求
type DeleteRequest struct {
	Key string
}

// DeleteResponse - Delete RPC 响应
type DeleteResponse struct {
	Success   bool
	Error     string
	RaftIndex int64
}

// ScanRequest - Scan RPC 请求
type ScanRequest struct {
	StartKey     string
	Limit        int32
	StartVersion int64
}

// ScanResponse - Scan RPC 响应
type ScanResponse struct {
	Pairs   []*KVPair
	HasMore bool
	Error   string
}

// KVPair - 键值对
type KVPair struct {
	Key     string
	Value   string
	Version int64
}

// WatchCreateRequest - Watch 创建请求
type WatchCreateRequest struct {
	Key          string
	StartVersion int64
}

// WatchCancelRequest - Watch 取消请求
type WatchCancelRequest struct {
	WatchId int64
}

// WatchRequest - Watch 请求
type WatchRequest struct {
	IsCreate bool
	Request  interface{}
}

// WatchEvent - Watch 事件
type WatchEvent struct {
	WatchId    int64
	Key        string
	OldValue   string
	NewValue   string
	OldVersion int64
	NewVersion int64
	EventType  string
	Timestamp  int64
	RaftIndex  int64
}

// ClusterStatusRequest - 集群状态请求
type ClusterStatusRequest struct {
	Level string
}

// ClusterStatusResponse - 集群状态响应
type ClusterStatusResponse struct {
	NodeId      int32
	NodeAddress string
	IsLeader    bool
	Term        int64
	LastApplied int64
	CommitIndex int64
	ClusterSize int32
	Peers       []*NodeStatus
	Status      string
}

// NodeStatus - 节点状态
type NodeStatus struct {
	Id         int32
	Address    string
	IsLeader   bool
	MatchIndex int64
	NextIndex  int64
	IsAlive    bool
}
